a = int(input("Enter first value"))
b = int(input("Enter second value"))
print("Addition result is: ",a+b)
print("Subtraction result is: ",a-b)
print("Multiplication result is ",a*b)
print("Division result is: ",a/b)
print("Reminder after division result is: ",a%b)
